backend:
  name: git-gateway
  branch: master

media_folder: static/media
public_folder: /media

collections:
  - label: "Pages"
    name: "pages"
    folder: 'content/pages'
    path: '{{path}}/index'
    create: true
    media_folder: ''
    public_folder: ''
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
      - { label: "Template Key", name: "templateKey", widget: "hidden", }
  
  - name: news
    label: News
    media_folder: ''
    public_folder: ''
    folder: content/news
    path: '{{path}}/index'
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }

  - name: 'global'
    label: 'Global Settings'
    delete: false
    editor: 
      preview: false
    files:
      - name: "carousel"
        label: "Carousel"
        file: 'content/settings/carousel/index.md'
        description: 'Home Page Carousel Images'
        media_folder: ''
        public_folder: ''
        fields:
          - { label: "Key", name: "key", widget: "hidden" }
          - label: "Images"
            name: "carouselImages"
            widget: "list"
            summary: '{{fields.image}}'
            fields: 
              - { label: "Image", name: "image", widget: "image" }
              - { name: alt, label: Alt Text, widget: "text" }
              - { name: author, label: Photographer Name, widget: "text", default: "Jane Doe Photos" }
              - { name: instagram, label: Instagram, widget: "text", default: "janeDoePhotos" }
