backend:
  name: git-gateway
  branch: master

media_folder: content/assets
public_folder: ../assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
  
  - label: "Pages"
    name: "pages"
    folder: 'content/pages'
    slug: '{{path}}'
    path: '{{path}}/index'
    create: true
    media_folder: ''
    public_folder: ''
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
