backend:
  name: git-gateway
  branch: master

media_folder: static/media
public_folder: /media

collections:
  - label: "Pages"
    name: "pages"
    folder: 'content/pages'
    path: '{{path}}/index'
    create: true
    media_folder: ''
    public_folder: ''
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
      - { label: "Template Key", name: "templateKey", widget: "hidden", }
  
  - name: blog
    label: Blog
    media_folder: ''
    public_folder: ''
    folder: content/blog
    path: '{{path}}/index'
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }

  - name: 'global'
    label: 'Global Settings'
    delete: false
    editor: 
      preview: false
    media_folder: ''
    public_folder: ''
    files:
      - name: "carousel"
        label: "Carousel"
        file: 'content/settings/carousel/index.md'
        description: 'Home Page Carousel Images'
        fields:
          - { label: "Key", name: "key", widget: "hidden" }
          - label: "Images"
            name: "carouselImages"
            widget: "list"
            summary: '{{fields.image}}'
            fields: 
              - { label: "Image", name: "image", widget: "image" }
